const niceChordNames = {
    "fifth": "5",
    "suspended fourth": "sus4",
    "suspended fourth seventh": "sus4 7",
    "augmented": "aug",
    "major seventh flat sixth": "Maj7♭6",
    "augmented seventh": "aug7",
    "major": "",
    "major seventh": "Maj7",
    "dominant seventh": "7",
    "sixth": "6",
    "major seventh sharp eleventh": "Maj7♯11",
    "lydian dominant seventh": "Lyd7",
    "minor augmented": "m aug",
    "minor": "m",
    "minor/major seventh": "mMaj7",
    "minor seventh": "m7",
    "minor sixth": "m6",
    "diminished": "dim",
    "half-diminished": "ø",
    "diminished seventh": "dim7",
    "dominant sharp ninth": "7♯9",
    "suspended second": "sus2",
    "eleventh": "11",
    "major ninth": "Maj9",
    "dominant ninth": "9",
    "sixth added ninth": "6 add9",
    "major thirteenth": "Maj13",
    "dominant thirteenth": "13",
    "major sharp eleventh (lydian)": "Maj♯11",
    "minor/major ninth": "mMaj9",
    "minor ninth": "m9",
    "minor thirteenth": "m13",
    "minor eleventh": "m11",
    "suspended fourth flat ninth": "sus4♭9",
    "altered": "alt",
    "dominant flat ninth": "7♭9"
  };
  
  const chordCommonnessHash = {
    "major": 1,
    "minor": 2,
    "dominant seventh": 3,
    "major seventh": 4,
    "minor seventh": 5,
    "sixth": 6,
    "diminished": 7,
    "augmented": 8,
    "suspended fourth": 9,
    "suspended second": 10,
    "half-diminished": 11,
    "diminished seventh": 12,
    "eleventh": 13,
    "dominant ninth": 14,
    "major ninth": 15,
    "minor ninth": 16,
    "dominant thirteenth": 17,
    "major thirteenth": 18,
    "minor eleventh": 19,
    "minor/major seventh": 20,
    "minor sixth": 21,
    "major seventh flat sixth": 22,
    "major seventh sharp eleventh": 23,
    "lydian dominant seventh": 24,
    "augmented seventh": 25,
    "dominant sharp ninth": 26,
    "major sharp eleventh (lydian)": 27,
    "suspended fourth seventh": 28,
    "sixth added ninth": 29,
    "minor augmented": 30,
    "minor/major ninth": 31,
    "minor thirteenth": 32,
    "suspended fourth flat ninth": 33,
    "altered": 34,
    "dominant flat ninth": 35
  };

const strangeChrods = ['minor augmented',]
export {niceChordNames,chordCommonnessHash,strangeChrods};
  