interface App {
  name: string;
  path: string;
}

import { ScaleDegree } from '@EarTrainers/DegreeTrainer/utils/presets';

interface Degree {
  degree: ScaleDegree; // semantic enum name
  symbol: string; // display symbol like I, IIb, V etc.
  distance: number;
  enable: boolean;
  interval: string;
}

interface UserProgress {
  level: number;
  unlocked: boolean;
  best: number;
  minTests: number;
  stars: number;
}

interface Shortcuts {
  [key: string]: number | string;
}

const apps: App[] = [
  { name: 'earTrainer', path: '/ear-trainer' },
  { name: 'chordTrainer', path: '/chord-trainer' },
];
const keyMap: { [key: string]: number } = {
  '1': 0,
  '2': 2,
  '3': 4,
  '4': 5,
  '5': 7,
  '6': 9,
  '7': 11,
  a: 1,
  s: 3,
  d: 6,
  f: 8,
  g: 10,
};

const shortcuts: Shortcuts = {
  I: 1,
  II: 2,
  III: 3,
  IV: 4,
  V: 5,
  VI: 6,
  VII: 7,
  IIb: 'a',
  IIIb: 's',
  Vb: 'd',
  VIb: 'f',
  VIIb: 'g',
};

const degrees: Record<ScaleDegree, Omit<Degree, 'degree' | 'enable'>> = {
  [ScaleDegree.First]: { symbol: 'I', distance: 0, interval: '1P' },
  [ScaleDegree.FlatTwo]: { symbol: 'IIb', distance: 1, interval: '2m' },
  [ScaleDegree.Two]: { symbol: 'II', distance: 2, interval: '2M' },
  [ScaleDegree.FlatThree]: { symbol: 'IIIb', distance: 3, interval: '3m' },
  [ScaleDegree.Three]: { symbol: 'III', distance: 4, interval: '3M' },
  [ScaleDegree.Fourth]: { symbol: 'IV', distance: 5, interval: '4P' },
  [ScaleDegree.FlatFifth]: { symbol: 'Vb', distance: 6, interval: '4A' },
  [ScaleDegree.Fifth]: { symbol: 'V', distance: 7, interval: '5P' },
  [ScaleDegree.FlatSix]: { symbol: 'VIb', distance: 8, interval: '6m' },
  [ScaleDegree.Six]: { symbol: 'VI', distance: 9, interval: '6M' },
  [ScaleDegree.FlatSeven]: { symbol: 'VIIb', distance: 10, interval: '7m' },
  [ScaleDegree.Seven]: { symbol: 'VII', distance: 11, interval: '7M' },
};

// Canonical order used across UI and masks
const ORDERED_DEGREES: ScaleDegree[] = [
  ScaleDegree.First,
  ScaleDegree.FlatTwo,
  ScaleDegree.Two,
  ScaleDegree.FlatThree,
  ScaleDegree.Three,
  ScaleDegree.Fourth,
  ScaleDegree.FlatFifth,
  ScaleDegree.Fifth,
  ScaleDegree.FlatSix,
  ScaleDegree.Six,
  ScaleDegree.FlatSeven,
  ScaleDegree.Seven,
];

// Default enabled set (matches old defaults: I, II, III)
const DEFAULT_ENABLED_DEGREES: ScaleDegree[] = [
  ScaleDegree.First,
  ScaleDegree.Two,
  ScaleDegree.Three,
];

const initialUserProgress: UserProgress[] = [
  {
    level: 1,
    unlocked: true,
    best: 0,
    minTests: 15,
    stars: 0,
  },
  {
    level: 2,
    unlocked: false,
    best: 0,
    minTests: 18,
    stars: 0,
  },
  {
    level: 3,
    unlocked: false,
    best: 0,
    minTests: 22,
    stars: 0,
  },
  {
    level: 4,
    unlocked: false,
    best: 0,
    minTests: 25,
    stars: 0,
  },
  {
    level: 5,
    unlocked: false,
    best: 0,
    minTests: 28,
    stars: 0,
  },
  {
    level: 6,
    unlocked: false,
    best: 0,
    minTests: 35,
    stars: 0,
  },
  {
    level: 7,
    unlocked: false,
    best: 0,
    minTests: 50,
    stars: 0,
  },
  {
    level: 8,
    unlocked: false,
    best: 0,
    minTests: 18,
    stars: 0,
  },
  {
    level: 9,
    unlocked: false,
    best: 0,
    minTests: 24,
    stars: 0,
  },
  {
    level: 10,
    unlocked: false,
    best: 0,
    minTests: 28,
    stars: 0,
  },
  {
    level: 11,
    unlocked: false,
    best: 0,
    minTests: 30,
    stars: 0,
  },
  {
    level: 12,
    unlocked: false,
    best: 0,
    minTests: 34,
    stars: 0,
  },
  {
    level: 13,
    unlocked: false,
    best: 0,
    minTests: 40,
    stars: 0,
  },
  {
    level: 14,
    unlocked: false,
    best: 0,
    minTests: 23,
    stars: 0,
  },
  {
    level: 15,
    unlocked: false,
    best: 0,
    minTests: 28,
    stars: 0,
  },
  {
    level: 16,
    unlocked: false,
    best: 0,
    minTests: 42,
    stars: 0,
  },
  {
    level: 17,
    unlocked: false,
    best: 0,
    minTests: 50,
    stars: 0,
  },
  {
    level: 18,
    unlocked: false,
    best: 0,
    minTests: 55,
    stars: 0,
  },
  {
    level: 19,
    unlocked: false,
    best: 0,
    minTests: 60,
    stars: 0,
  },
  {
    level: 20,
    unlocked: false,
    best: 0,
    minTests: 70,
    stars: 0,
  },
];

const DEGREES_MAP: { [key: string]: boolean[] } = {
  LEVEL_1: [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
  ],
  LEVEL_2: [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
  ],
  LEVEL_3: [
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
  ],
  LEVEL_4: [
    true,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
  ],
  LEVEL_5: [
    true,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    true,
    false,
    true,
  ],
  LEVEL_6: [
    true,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    true,
    false,
    true,
  ],
  LEVEL_7: [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    true,
    false,
    true,
  ],
  LEVEL_8: [
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
  ],
  LEVEL_9: [
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
  ],
  LEVEL_10: [
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
  ],
  LEVEL_11: [
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    true,
    false,
  ],
  LEVEL_12: [
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
  ],
  LEVEL_13: [
    true,
    true,
    true,
    true,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
  ],
  LEVEL_14: [
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    true,
  ],
  LEVEL_15: [
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    true,
    true,
  ],
  LEVEL_16: [
    true,
    false,
    false,
    true,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    true,
  ],
  LEVEL_17: [
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    true,
  ],
  LEVEL_18: [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    true,
    true,
  ],
  LEVEL_19: [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    true,
    true,
  ],
  LEVEL_20: [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
  ],
};

const NOTES_MAP: { [key: string]: string } = {
  LEVEL_1: '1 7',
  LEVEL_2: '1 5 7',
  LEVEL_3: '1 3 5 7',
  LEVEL_4: '1 2 3 5 7',
  LEVEL_5: '1 2 3 5 6 7',
  LEVEL_6: '1 2 3 4 5 6 7',
  LEVEL_7: '1 2 3 4 #4 5 6 7',
  LEVEL_8: '1 2 b3',
  LEVEL_9: '1 2 b3 5',
  LEVEL_10: '1 2 b3 5 b6',
  LEVEL_11: '1 2 b3 5 b6 b7',
  LEVEL_12: '1 2 b3 4 5 b6 b7',
  LEVEL_13: '1 b2 2 b3 4 5 b6 b7',
  LEVEL_14: '1 4 5 7',
  LEVEL_15: '1 4 5 b7 7',
  LEVEL_16: '1 b3 3 4 5 b7 7',
  LEVEL_17: '1 b2 2 b3 3 4 5 b7 7',
  LEVEL_18: '1 b2 2 b3 3 4 #4 5 b7 7',
  LEVEL_19: '1 b2 2 b3 3 4 #4/b5 5 b7 7',
  LEVEL_20: '1 b2 2 b3 3 4 #4 b5 5 b6 6 b7 7',
};

const SolfegeMapping = {
  I: 'Do',
  II: 'Re',
  III: 'Mi',
  IV: 'Fa',
  V: 'Sol',
  VI: 'La',
  VII: 'Ti',
  IIb: 'Ra',
  IIIb: 'Me',
  Vb: 'Se',
  VIb: 'Le',
  VIIb: 'Te',
};

export {
  apps,
  keyMap,
  degrees,
  ORDERED_DEGREES,
  DEFAULT_ENABLED_DEGREES,
  initialUserProgress,
  SolfegeMapping,
  shortcuts,
  DEGREES_MAP,
  NOTES_MAP,
};
export type { App, Degree, UserProgress, Shortcuts };
