import { DegreePreset, ScaleDegree } from '@EarTrainers/DegreeTrainer/utils/presets';

// Define modes directly with semantic ScaleDegree lists for clarity
export const freeModePresets: Record<string, DegreePreset> = {
  ionian: {
    id: 'ionian',
    name: 'Ionian (Major)',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.Three,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.Six,
      ScaleDegree.Seven,
    ],
    source: 'free',
  },
  dorian: {
    id: 'dorian',
    name: 'Dorian',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.FlatThree,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.Six,
      ScaleDegree.FlatSeven,
    ],
    source: 'free',
  },
  phrygian: {
    id: 'phrygian',
    name: 'Phrygian',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.FlatTwo,
      ScaleDegree.FlatThree,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.FlatSix,
      ScaleDegree.FlatSeven,
    ],
    source: 'free',
  },
  lydian: {
    id: 'lydian',
    name: 'Lydian',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.Three,
      ScaleDegree.FlatFifth,
      ScaleDegree.Fifth,
      ScaleDegree.Six,
      ScaleDegree.Seven,
    ],
    source: 'free',
  },
  mixolydian: {
    id: 'mixolydian',
    name: 'Mixolydian',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.Three,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.Six,
      ScaleDegree.FlatSeven,
    ],
    source: 'free',
  },
  aeolian: {
    id: 'aeolian',
    name: 'Aeolian (Natural Minor)',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.FlatThree,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.FlatSix,
      ScaleDegree.FlatSeven,
    ],
    source: 'free',
  },
  locrian: {
    id: 'locrian',
    name: 'Locrian',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.FlatTwo,
      ScaleDegree.FlatThree,
      ScaleDegree.Fourth,
      ScaleDegree.FlatFifth,
      ScaleDegree.FlatSix,
      ScaleDegree.FlatSeven,
    ],
    source: 'free',
  },
  naturalMinor: {
    id: 'naturalMinor',
    name: 'Natural Minor',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.FlatThree,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.FlatSix,
      ScaleDegree.FlatSeven,
    ],
    source: 'free',
  },
  harmonicMinor: {
    id: 'harmonicMinor',
    name: 'Harmonic Minor',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.FlatThree,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.FlatSix,
      ScaleDegree.Seven,
    ],
    source: 'free',
  },
  melodicMinor: {
    id: 'melodicMinor',
    name: 'Melodic Minor',
    enabledDegrees: [
      ScaleDegree.First,
      ScaleDegree.Two,
      ScaleDegree.FlatThree,
      ScaleDegree.Fourth,
      ScaleDegree.Fifth,
      ScaleDegree.Six,
      ScaleDegree.Seven,
    ],
    source: 'free',
  },
};

export const getPresetById = (id: string): DegreePreset | undefined =>
  freeModePresets[id];
